<html>
<head>
    <title>PEMJUMLAHAN</title>
</head>

<body>
    <h5> APLIKASI PERHITUNGAN MATEMATIKA</h5>
    <h5> LINDON 221510031</h5>
    <form action="proses.php" method="POST">
        Bilangan 1 : <br>
        <input type="text" name="txtbil1"><br>
        Bilangan 2 : <br>
        <input type="text" name="txtbil2"><br>
        <button type="submit">HITUNG</button>
    </form>
</body>
</html>